version: "3"
services:
    server:
        container_name: "Server"
        build: "./server"
        depends_on:
            - mongo
        links:
            - mongo
        working_dir: "/app/server"
        ports:
            - "8080:8080"
        env_file:
            - "./server/.env"
        restart: always
        command: sh -c "npm install && npm run production"
    client:
        container_name: "Client"
        build: "./client"
        working_dir: "/app/client"
        ports:
            - "80:3000"
        env_file:
            - "./client/.env"
        restart: always
    mongo:
        container_name: "MongoDB"
        image: mongo
        restart: always
        env_file:
            - ".env"
        volumes:
            - "./volume_data/mongo:/data/db"