version: "3"
services:
    server:
        container_name: "Server"
        build: "./server"
        ports:
            - "8080:8080"
        restart: always
    client:
        container_name: "Client"
        build: "./client"
        ports:
            - "80:3000"
        restart: always
    mongo:
        container_name: "MongoDB"
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: localhost
            MONGO_INITDB_ROOT_PASSWORD: password
        volumes:
            - "./app/mongo-volume:/data/db"
        ports:
            - 27017:27017
    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: localhost
            ME_CONFIG_MONGODB_ADMINPASSWORD: password
