version: "3"
services:
    server:
        build: "./server"
        ports:
            - "8080:8080"
    client:
        build: "./client"
        ports:
            - "80:3000"
    mongo:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: localhost
            MONGO_INITDB_ROOT_PASSWORD: password
    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: localhost
            ME_CONFIG_MONGODB_ADMINPASSWORD: password
