version: "3"
services:
    server:
        container_name: "Server"
        build: "./server"
        depends_on: 
            - mongo
        working_dir: "/app/server"
        volumes:
            - "./server:/app/server:cached"
        ports:
            - "8080:8080"
        restart: always
        command: sh -c "npm install && npm start"
    client:
        container_name: "Client"
        build: "./client"
        working_dir: "/app/client"
        volumes:
            - "./client:/app/client:cached"
        ports:
            - "80:3000"
        restart: always
        environment:
            - NODE_ENV=development
            - CHOKIDAR_USEPOLLING=true
    mongo:
        container_name: "MongoDB"
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: localhost
            MONGO_INITDB_ROOT_PASSWORD: password
        volumes:
            - "./app/mongo-volume:/data/db"
        ports:
            - 27017:27017
    mongo-express:
        container_name: "Mongo-Express"
        image: mongo-express
        depends_on: 
            - mongo
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: localhost
            ME_CONFIG_MONGODB_ADMINPASSWORD: password
